#!/bin/bash
#
# IBC + IB Gateway Setup Script for STOXX50 Trade Filter
# Sets up headless IBKR API access using IB Gateway + IBC
#
# IBC automates IB Gateway login, handling daily restarts and 2FA
# This is the correct solution for headless TWS API access
#
# Usage: ./scripts/setup_ibc.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Versions (update as needed)
IBC_VERSION="3.18.0"
GATEWAY_VERSION="10.30.1t"  # 't' = stable

# Directories
IBC_DIR="$HOME/ibc"
GATEWAY_DIR="$HOME/Jts"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "=================================================="
echo "  IBC + IB Gateway Setup for STOXX50 Trade Filter"
echo "=================================================="
echo -e "${NC}"
echo ""
echo "This script will install:"
echo "  1. IB Gateway (lightweight, no GUI)"
echo "  2. IBC (automates login)"
echo "  3. Xvfb (virtual display for headless)"
echo "  4. Systemd service (auto-start)"
echo ""

# Check for required tools
echo -e "${CYAN}Checking prerequisites...${NC}"

if ! command -v java &> /dev/null; then
    echo -e "${YELLOW}Java not found. Installing OpenJDK...${NC}"
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jre-headless
fi

if ! command -v unzip &> /dev/null; then
    sudo apt-get install -y unzip
fi

# Install Xvfb for headless operation
if ! command -v Xvfb &> /dev/null; then
    echo -e "${YELLOW}Installing Xvfb for headless operation...${NC}"
    sudo apt-get install -y xvfb
fi

echo -e "${GREEN}Prerequisites OK${NC}"
echo ""

# Get trading mode
echo "Select trading mode:"
echo "  1) Paper trading (recommended for testing)"
echo "  2) Live trading"
echo ""
read -p "Enter choice [1/2]: " mode_choice
case $mode_choice in
    1)
        TRADING_MODE="paper"
        API_PORT=4002
        ;;
    2)
        TRADING_MODE="live"
        API_PORT=4001
        ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac

echo ""
echo -e "${CYAN}Setting up ${TRADING_MODE^^} trading on port ${API_PORT}${NC}"
echo ""

# Get IBKR credentials
echo -e "${CYAN}Enter your IBKR credentials:${NC}"
read -p "IBKR Username: " IBKR_USER
read -s -p "IBKR Password: " IBKR_PASS
echo ""
echo ""

# Create directories
echo "Creating directories..."
mkdir -p "$IBC_DIR"
mkdir -p "$GATEWAY_DIR"
mkdir -p "$HOME/.ibc"

# Download IB Gateway if not present
GATEWAY_INSTALLER="$HOME/ibgateway-${GATEWAY_VERSION}-standalone-linux-x64.sh"
if [ ! -f "$GATEWAY_DIR/ibgateway/$GATEWAY_VERSION/ibgateway" ] && [ ! -d "$GATEWAY_DIR/ibgateway" ]; then
    echo ""
    echo -e "${CYAN}Downloading IB Gateway...${NC}"
    echo "Please download IB Gateway manually from:"
    echo "  https://www.interactivebrokers.com/en/trading/ibgateway-stable.php"
    echo ""
    echo "Select: IB Gateway for Linux"
    echo "Save to: $HOME/"
    echo ""
    read -p "Press Enter when downloaded..."

    if [ -f "$HOME/ibgateway-"*"-standalone-linux-x64.sh" ]; then
        GATEWAY_INSTALLER=$(ls -1 "$HOME/ibgateway-"*"-standalone-linux-x64.sh" | head -1)
        echo "Found: $GATEWAY_INSTALLER"
        chmod +x "$GATEWAY_INSTALLER"
        echo "Installing IB Gateway..."
        "$GATEWAY_INSTALLER" -q -dir "$GATEWAY_DIR"
        rm "$GATEWAY_INSTALLER"
    else
        echo -e "${RED}IB Gateway installer not found${NC}"
        echo "Please download from https://www.interactivebrokers.com/en/trading/ibgateway-stable.php"
        exit 1
    fi
else
    echo -e "${GREEN}IB Gateway already installed${NC}"
fi

# Find gateway path
GATEWAY_PATH=$(find "$GATEWAY_DIR" -name "ibgateway" -type f 2>/dev/null | head -1)
if [ -z "$GATEWAY_PATH" ]; then
    GATEWAY_PATH="$GATEWAY_DIR/ibgateway/$(ls "$GATEWAY_DIR/ibgateway" 2>/dev/null | head -1)"
fi
echo "Gateway path: $GATEWAY_PATH"

# Download IBC
echo ""
echo -e "${CYAN}Downloading IBC ${IBC_VERSION}...${NC}"
IBC_ZIP="/tmp/IBCLinux-${IBC_VERSION}.zip"
curl -L -o "$IBC_ZIP" "https://github.com/IbcAlpha/IBC/releases/download/${IBC_VERSION}/IBCLinux-${IBC_VERSION}.zip"
unzip -o "$IBC_ZIP" -d "$IBC_DIR"
chmod +x "$IBC_DIR"/*.sh
echo -e "${GREEN}IBC installed to $IBC_DIR${NC}"

# Create IBC config
echo ""
echo "Creating IBC configuration..."
cat > "$HOME/.ibc/config.ini" << EOF
# IBC Configuration for STOXX50 Trade Filter
# Generated by setup_ibc.sh

LogToConsole=yes
FIX=no
IbLoginId=$IBKR_USER
IbPassword=$IBKR_PASS
TradingMode=$TRADING_MODE

# Accept incoming API connections
AcceptIncomingConnectionAction=accept

# Auto-restart settings
AcceptNonBrokerageAccountWarning=yes
AllowBlindTrading=yes
DismissPasswordExpiryWarning=yes
DismissNSEComplianceNotice=yes

# 2FA - IBC will wait for you to approve on phone
# For fully automated 2FA, you need IBKR Mobile app configured
SecondFactorAuthenticationExitInterval=60
ExistingSessionDetectedAction=primary

# API Settings
OverrideTwsApiPort=$API_PORT
ReadOnlyLogin=no

# Auto-closedown - disable for 24/7 operation
# IbAutoClosedown=no
EOF

chmod 600 "$HOME/.ibc/config.ini"
echo -e "${GREEN}IBC config created at $HOME/.ibc/config.ini${NC}"

# Create startup script
echo ""
echo "Creating startup script..."
cat > "$IBC_DIR/start-gateway.sh" << EOF
#!/bin/bash
# Start IB Gateway with IBC (headless)

export DISPLAY=:99

# Start Xvfb if not running
if ! pgrep -x "Xvfb" > /dev/null; then
    Xvfb :99 -screen 0 1024x768x24 &
    sleep 2
fi

# Find IB Gateway
TWS_MAJOR_VRSN=\$(ls "$GATEWAY_DIR/ibgateway" 2>/dev/null | sort -V | tail -1)
if [ -z "\$TWS_MAJOR_VRSN" ]; then
    echo "IB Gateway not found in $GATEWAY_DIR/ibgateway"
    exit 1
fi

export TWS_MAJOR_VRSN

# Start IBC
cd "$IBC_DIR"
./gatewaystart.sh -g "\$TWS_MAJOR_VRSN" --ibc-path "$IBC_DIR" --ibc-ini "$HOME/.ibc/config.ini" --gateway-path "$GATEWAY_DIR/ibgateway/\$TWS_MAJOR_VRSN"
EOF

chmod +x "$IBC_DIR/start-gateway.sh"

# Create stop script
cat > "$IBC_DIR/stop-gateway.sh" << EOF
#!/bin/bash
# Stop IB Gateway

pkill -f "ibgateway" || true
pkill -f "Xvfb :99" || true
echo "IB Gateway stopped"
EOF

chmod +x "$IBC_DIR/stop-gateway.sh"

# Create systemd service
echo ""
echo "Creating systemd service..."
mkdir -p "$HOME/.config/systemd/user"
cat > "$HOME/.config/systemd/user/ibgateway.service" << EOF
[Unit]
Description=IB Gateway with IBC
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$IBC_DIR/start-gateway.sh
ExecStop=$IBC_DIR/stop-gateway.sh
Restart=on-failure
RestartSec=30

# Environment
Environment=DISPLAY=:99

[Install]
WantedBy=default.target
EOF

# Reload systemd
systemctl --user daemon-reload

echo -e "${GREEN}Systemd service created${NC}"
echo ""

# Update project config.yaml
CONFIG_FILE="$PROJECT_DIR/config.yaml"
if [ -f "$CONFIG_FILE" ]; then
    echo "Updating config.yaml..."
    "$PROJECT_DIR/venv/bin/python" << EOF
import yaml

with open('$CONFIG_FILE', 'r') as f:
    config = yaml.safe_load(f)

if 'ibkr' not in config:
    config['ibkr'] = {}

config['ibkr']['enabled'] = True
config['ibkr']['host'] = '127.0.0.1'
config['ibkr']['port'] = $API_PORT
config['ibkr']['client_id'] = 1
config['ibkr']['timeout'] = 15

with open('$CONFIG_FILE', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

print("Updated config.yaml")
EOF
fi

echo ""
echo -e "${GREEN}=================================================="
echo "  Setup Complete!"
echo "==================================================${NC}"
echo ""
echo -e "${CYAN}To start IB Gateway:${NC}"
echo "  $IBC_DIR/start-gateway.sh"
echo ""
echo -e "${CYAN}Or use systemd:${NC}"
echo "  systemctl --user start ibgateway"
echo "  systemctl --user enable ibgateway  # Auto-start on boot"
echo ""
echo -e "${CYAN}To stop:${NC}"
echo "  $IBC_DIR/stop-gateway.sh"
echo "  # or: systemctl --user stop ibgateway"
echo ""
echo -e "${CYAN}View logs:${NC}"
echo "  journalctl --user -u ibgateway -f"
echo ""
echo -e "${YELLOW}IMPORTANT: First start requires 2FA approval on your phone!${NC}"
echo ""
echo -e "${CYAN}Test connection:${NC}"
echo "  ./venv/bin/python -c \""
echo "from ibkr_provider import IBKRProvider"
echo "p = IBKRProvider(port=$API_PORT)"
echo "if p.connect():"
echo "    print(f'Euro Stoxx 50: {p.get_index_price()}')"
echo "    p.disconnect()"
echo "\""
echo ""
echo -e "${CYAN}Config files:${NC}"
echo "  IBC config: $HOME/.ibc/config.ini"
echo "  Gateway:    $GATEWAY_DIR/ibgateway/"
echo ""
